const HOUSE_EDGE_PERCENT = 1;
const GROWTH_K = 0.001;
const SCHEDULER_INTERVAL_MS = 10000;
const PROCESSING_MARGIN_MS = 500;
const MAX_ACCEPTABLE_DRIFT_MS = SCHEDULER_INTERVAL_MS + PROCESSING_MARGIN_MS;

export const provablyFairConfig = {
  HOUSE_EDGE_PERCENT,
  GROWTH_K,
  SCHEDULER_INTERVAL_MS,
  PROCESSING_MARGIN_MS,
  MAX_ACCEPTABLE_DRIFT_MS,
};
